### PR TITLE
Exclude packages

### PR DESCRIPTION
**Pull request by juliangut**
Add a list of packages to be excluded both on outdated and upgradable lists

```
./bin/climb outdated --exclude=doctrine/cache,willdurand/negotiation
```

Covers #45

### CODE REVIEW

**Comment by vinkla** [comment]
Thanks!

**Comment by juliangut** [comment]
I only considered this option for packages checking, but wouldn't it be usefull on update command?

**Comment by vinkla** [comment]
No, I don't think so. The update command is more of a bulk update.

**Comment by juliangut** [comment]
:+1:

**Pull request merged**
