### PR TITLE
packages control flags

### PR DESCRIPTION
**Pull request by juliangut**
Once 0.7 is out...

Added control flags to cover #21 and #23
- --no-outdated to exclude outdated packages
- --no-upgradable to exclude upgradable packages

### CODE REVIEW

**Comment by vinkla** [comment]
Thanks for being quick. I'm still not sure about the `--fail` flag.

**Comment by juliangut** [comment]
This is the use case in a CI process:

I want to check if my project has outdated dependencies, and in case it has I want my process to stop and yield a message for the team to update outdated dependencies before considering the build is correct.

Right now climb always returns with 0, meaning it doesn't matter if you have outdated/upgradable dependencies or not the execution always exits successfully, in order to change this behavior (and not make it the default one) there is the --fail flag

Consider that when executing climb directly on the console you don't get to see if the execution was successful or not because stdout and stderr are both your terminal, but for a CI process there is a difference in that it allows the process to know if there was any error.

If I'm to choose I'd just make climb fail always if there was an outdated or upgradable dep. In this case maybe allow you to control it with a `--no-fail` flag to opt-out instead of opting in. Anyway I haven't added this but the opposite to keep current behavior unchanged

I hope this clarifies the scenario

**Comment by vinkla** [comment]
Okay, thanks for explaining. Makes more sense now for what you're trying to achieve. IMO (as you also wrote) we should just make it return false whenever there are either outdated or upgradable packages available. Could you remove the fail flag from this pull request and then I can fix the None-Zero status codes once this is merged.

**Comment by juliangut** [comment]
What are your thoughts on this?

**Comment by vinkla** [comment]
Much better, I'll take a look tomorrow.

**Comment by vinkla** [comment]
Thanks.

**Pull request merged**
