### PR TITLE
Update commands

### LINKED ISSUE #1: Add Update Command
We want to be able to update the composer packages bu running:

```bash
climb update
```
And if we want to update to breaking versions:
```bash
climb update --all
```

### PR DESCRIPTION
**Pull request by joecohens**
Move commands to their own folder and namespace
Update commands

This closes #1 and #20.

### CODE REVIEW

**Comment by vinkla** [comment]
Awesome work @joecohens! This feature has been requested by many and we haven't had the time to add it. I'll definitely merge this right away.

**Comment by vinkla** [comment]
Just saw you hadn't removed the [WIP] from the title. This is such an awesome feature I just merged it in.  Is there anything else you want to add before we release this in the next version? I'll hold off you want to add anything else.

**Comment by joecohens** [comment]
Lol don't worry :) I left it has WIP so that we discuss command naming and version constrains. Maybe we can set an option to change the constrain?

**Comment by vinkla** [comment]
How do you mean?

**Comment by joecohens** [comment]
Exactly

**Comment by vinkla** [comment]
That is a good idea. Btw, is it possible to update multiple versions with this PR? Like `^4.8 || ^5.0` and `^5.0.* || ^5.1.*`.

**Comment by joecohens** [comment]
I haven't tried the piped versions, but it should work I'll test it tomorrow :)

**Comment by vinkla** [comment]
:+1:

**Pull request merged**
