### PR TITLE
outdated/upgradable and fail flags

### PR DESCRIPTION
**Pull request by juliangut**
Added flags to control outdated command:
- --no-outdated to exclude outdated packages
- --no-upgradable to eclude upgradable packages
- --fail to return 1 if outdated or/and upgradable

Covers #21 and #23

### CODE REVIEW

**Comment by vinkla** [comment]
Great work. Why do we need the `--fail` flag? Could you describe use case for this?

**Comment by juliangut** [comment]
Sure
It is meant for a CI process, during integration I can decide I want the process to fail in case there are outdated dependencies so I have to fix them before, I'd use:

```
./vendor/bin/climb outdated --outdated --fail
```

this Outdated command will look only for outdated packages AND in case there is any it will raise an error (--fail)

As I commented on the issue I don't see the benefit on failing on upgradable packages, anyway with this flags you can do it in case you want to always have the latest packages.

**Comment by juliangut** [comment]
Changed to opt-out flags, `no-outdated` and `no-upgradable`
I'm developing a grunt task to use climb and making them opt-out flags seams more reasonable

To reproduce the example I wrote on a previous comment:

```
./vendor/bin/climb outdated --no-upgradable --fail
```

**Comment by vinkla** [comment]
Thanks for this. I've made some change to the `develop` branch. Could you redo this for the develop branch? Or if it is okay with you, I can add this features directly?

About the `--fail` flag. What does other packages use?

**Pull request closed without merging**
