### PR TITLE
Enable gzip compression of .phar

### PR DESCRIPTION
**Pull request by mbrodala**
This reduces the size of the .phar from 1.8M to 591K

### CODE REVIEW

**Comment by vinkla** [comment]
Awesome! Thank you.

**Comment by vinkla** [comment]
@mbrodala maybe we could exclude even more files?

**Comment by mbrodala** [comment]
@vinkla I'd assume yes but first I'd need to have a closer look at all pulled packages.

**Comment by vinkla** [comment]
Yeah, true. If you feel up for it please submit a pull request.

**Comment by vinkla** [comment]
Doesn't work?

```sh
Fatal error: Uncaught ErrorException: proc_open(): unable to create pipe Too many open files in phar:///usr/local/Cellar/box/2.5.3/libexec/box-2.5.3.phar/src/vendors/symfony/console/Application.php:978
Stack trace:
#0 [internal function]: KevinGH\Box\Application->KevinGH\Box\{closure}(2, 'proc_open(): un...', 'phar:///usr/loc...', 978, Array)
#1 phar:///usr/local/Cellar/box/2.5.3/libexec/box-2.5.3.phar/src/vendors/symfony/console/Application.php(978): proc_open('stty -a | grep ...', Array, NULL, NULL, NULL, Array)
#2 phar:///usr/local/Cellar/box/2.5.3/libexec/box-2.5.3.phar/src/vendors/symfony/console/Application.php(788): Symfony\Component\Console\Application->getSttyColumns()
#3 phar:///usr/local/Cellar/box/2.5.3/libexec/box-2.5.3.phar/src/vendors/symfony/console/Application.php(749): Symfony\Component\Console\Application->getTerminalDimensions()
#4 phar:///usr/local/Cellar/box/2.5.3/libexec/box-2.5.3.phar/src/vendors/symfony/console/Application.php(679): Symfony\Component\Console\Application->getTerminalWidth()
#5 phar in phar:///usr/local/Cellar/box/2.5.3/libexec/box-2.5.3.phar/src/vendors/symfony/console/Application.php on line 978
```

Works fine when I remove the compression though.

**Comment by mbrodala** [comment]
Works fine here though. I just built the `climb.phar` from the latest master and ran it in a project directory where outdated dependencies where shown just fine. Did you invoke it in any special way?

**Comment by vinkla** [comment]
Just ran `box build`.

**Comment by mbrodala** [comment]
Same here. I was using `Box version 2.6.0 build 34259e688bad430cf6e4418d4682d7650c7b90f1` and [the manual](http://php.net/manual/en/phar.compress.php) doesn't state any special requirements to use gzipped `.phar` files.

**Comment by mbrodala** [comment]
Sounds like you stumbled over [this one](https://github.com/box-project/box2/issues/80) though. What PHP version are you using? It's 5.5.9 here.

**Comment by vinkla** [comment]
I'm using PHP 7.0

**Comment by mbrodala** [comment]
Interesting then. Are you able to test with PHP 5.x too?

**Comment by vinkla** [comment]
Nope.

**Pull request merged**
