### PR TITLE
output formatters

### PR DESCRIPTION
**Pull request by juliangut**
Output formatting `--format`flag

Supported formats:
- console, outputs pretty text, it is the default format, respects former behavior
- json, outputs JSON object with "outdated" and "upgradable" keys
- xml, outputs XML with "climb" base element and "outdated" and "upgradable" as its children

Update of PR #40

### CODE REVIEW

**Comment by juliangut** [comment]
Have a look at this too

**Comment by juliangut** [comment]
How do you feel about this PR?

**Comment by vinkla** [comment]
I like the idea but I would like to have tests before adding this. First we need to create tests for the commands and then tests for the output formatters before we can merge this.

**Comment by juliangut** [comment]
Are we close to having those tests?

**Comment by vinkla** [comment]
Not at the moment, no. Sorry. If you feel up for it we would be glad to take a look at any pull request you send our way.

**Comment by vinkla** [comment]
Thanks but I've deprecated this package now since it is [added to to Composer](https://medium.com/@vinkla/find-outdated-packages-with-composer-968828c1d80a) out of the box.

**Pull request closed without merging**
