### PR TITLE
Allow user to define composer files directory

### PR DESCRIPTION
**Pull request by juliangut**
New "directory" argument, users can define path to directory with composer files (.lock and .json)
Useful for building and CI processes

### CODE REVIEW

**Comment by vinkla** [comment]
Thanks fork this. I've made some change to the `develop` branch. Could you redo this for the develop branch? Or if it is okay with you, I can add these features directly?

**Comment by vinkla** [comment]
Why did you close it?

**Comment by juliangut** [comment]
Created #41 to include this on develop branch

**Comment by vinkla** [comment]
Okay.

**Pull request closed without merging**
